# platform :ios, '8.0'

target 'U' do
  use_frameworks!
  
  pod 'UMCCommon', '2.1.1'
  pod 'UMCAnalytics', '~> 6.0.5'
  pod 'UMCSecurityPlugins', '~> 1.0.6'
  pod 'UMCCommonLog', '~> 1.0.0'
  pod 'UMCPush', '~> 3.2.4'
  pod 'LLSwitch', '1.0.4'
  pod 'PathMenu', :git => 'https://github.com/BrooksWon/PathMenu.git'#暂时写自己的库，等待master合并我的PR后再替换成master
  
  pod 'SCLAlertView', :git => 'https://github.com/vikmeup/SCLAlertView-Swift.git'
  
  # pod 'GlitchLabel', '2.0.0'   GlitchLabel.source = { :git => 'https://github.com/BrooksWon/GlitchLabel.git'}
  pod 'GlitchLabel', :git => 'https://github.com/BrooksWon/GlitchLabel.git'#暂时写自己的库，等待master合并我的PR后再替换成master

  pod 'LTMorphingLabel'
  pod 'SwiftyJSON', '~>4.0.0'
  pod 'iRate', '~>1.12.1'
  pod 'Alamofire', '~> 4.7'
  pod 'HandyJSON', '~> 5.0.0'
  pod 'Bugly', '~> 2.5.0'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'MJRefresh'

end
